### ISSUE TITLE
Fix footer jumping and hiding input bar on mobile

### ISSUE THREAD

**Issue by BhavyaCodes** [Juggernaut9/url-shortener-ts-frontend#1]
![Screenshot_2020-11-12-09-17-41-31.jpg](https://user-images.githubusercontent.com/58269749/98893230-02904300-24c8-11eb-80a8-a0350bf0b210.jpg)

**Comment by Juggernaut9** [comment]
![Screenshot_2020-11-12-09-17-41-31.jpg](https://user-images.githubusercontent.com/58269749/98893190-f2786380-24c7-11eb-9584-8f9ce7f186df.jpg)

**Comment by ThisTarunGupta** [comment]
I would like to work on this **issue**.

Please assign and guide to me
@tarung10

**Comment by BhavyaCodes** [comment]
hey @tarung10 , how is the progress?

**Comment by BhavyaCodes** [comment]
one solution you can try is scroll to the input when its focussed, Im not sure if that will work however

**Comment by BhavyaCodes** [comment]
I'm gonna start working on this today or tomorrow

**Comment by BhavyaCodes** [comment]
Fixed, the title now gets hidden on small displays when input bar is focussed
